publisher:
    visual_marker:
        topic: /drow/visualization_marker_front
        queue_size: 1
        latch: false

    detections:
        topic: /drow/detected_persons_front
        queue_size: 1
        latch: false

subscriber:
    scan:
        topic: /laser_front/scan
        queue_size: 1
