publisher:
    visual_marker:
        topic: /drow/visualization_marker_rear
        queue_size: 1
        latch: false

    detections:
        topic: /drow/detected_persons_rear
        queue_size: 1
        latch: false

subscriber:
    scan:
        topic: /laser_rear/scan
        queue_size: 1
