publisher:
    scan:
        topic: /crowdrep_bot/scan_front
        queue_size: 1
        latch: false

    robot_tf:
        topic: /crowdrep_bot/robot_tf
        queue_size: 1
        latch: false

    robot_vis:
        topic: /vis/robot
        queue_size: 1
        latch: false

    objects_vis:
        topic: /vis/objects
        queue_size: 1
        latch: false

    frame_id: myFixedFrame
subscriber:
    cmd:
        topic: /robot/xxxx
        queue_size: 1
